version: '3.8'

services:
  jenkins:
    image: user_jenkins
    privileged: true
    user: root
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/home/faniry/jenkins_compose/jenkins_configuration:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"