apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match **>
      @type elasticsearch
      host elasticsearch.logging.svc.cluster.local
      port 9200
      logstash_format true
      flush_interval 5s
    </match>

