version: '3.3'
services:
  db_ostie:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --server-id=1
    restart: always
    container_name: db_ostie
    environment:
      MYSQL_DATABASE: 'ostie'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ConsteUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ghjhjhhjgh'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mf-ufuç'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3390:3306'
    #expose:
      # Opens port 3306 on the container
      #- '3306'
      # Where our data will be persisted
    volumes:
      - /home/debian/mysql_ostie/my.cnf:/etc/my.cnf:ro
      - my-db2:/var/lib/mysql
      - /home/debian/mysql_ostie:/var/log/:rw
      #- /home/ubuntu/mysql_ostie/etc:/etc/


   #Names our volume
volumes:
  my-db2:
