version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
# These ports are in format < host-port>:< container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "172.22.1.10:8181:81" # Admin Web Port
# Uncomment this if IPv6 is not enabled on your host
# DISABLE_IPV6: 'true'

    volumes:
# le dossier ou mettre les fichiers de ngnix proxy manager
      - ./home/debian/docker/nginx/data:/data
      - ./home/debian/docker/nginx/letsencrypt:/etc/letsencrypt
    #  - ./home/debian/docker/nginx/_hsts.conf:/app/templates/_hsts.conf:rw
      - /etc/localtime:/etc/localtime:ro
 # networks:
   # - mynetwork
#networks:
   #mynetwork:
    #driver: bridge

