global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['172.22.1.57:9100','172.22.1.98:9100']


  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.22.1.57:8080','172.22.1.98:8080]



alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'